### ISSUE TITLE
Cannot find module 'ajv/dist/core'

### ISSUE THREAD

**Issue by Rikihanks** [seriousme/fastify-openapi-glue#264]
Hello!
It seems that there is a problem with a dependency of ajv, when using openapi-glue v2.6.1 it throws an error whenever I want to run the project. Here is the stack:

`Error: Cannot find module 'ajv/dist/core'
Require stack:
- /proyectos/txManagerApi/txmanagerApi/node_modules/ajv-draft-04/dist/index.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/@seriousme/openapi-schema-validator/index.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/fastify-openapi-glue/lib/parser.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/fastify-openapi-glue/index.js
- /proyectos/txManagerApi/txmanagerApi/dist/app.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/util.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/start.js
- /proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/proyectos/txManagerApi/txmanagerApi/node_modules/ajv-draft-04/dist/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/proyectos/txManagerApi/txmanagerApi/node_modules/ajv-draft-04/dist/index.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/@seriousme/openapi-schema-validator/index.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/fastify-openapi-glue/lib/parser.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/fastify-openapi-glue/index.js',
    '/proyectos/txManagerApi/txmanagerApi/dist/app.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/util.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/start.js',
    '/proyectos/txManagerApi/txmanagerApi/node_modules/fastify-cli/cli.js'
  ]
}`

It works fine on the 2.5 version of the openapi-glue plugin.

**Comment by seriousme** [comment]
Good to see you found a solution !
