### ISSUE TITLE
[bug?] Validation errors not handled in TypeScript

### ISSUE THREAD

**Issue by clairefro** [seriousme/fastify-openapi-glue#314]
I used `fastify-openapi-glue` with a vanilla JS project and it worked great: 
https://github.com/Postman-Student-Program/restaurant-api-example/tree/chapter-3-persisting-data

Now I'm using TypeScript with the same setup but validation errors (`400`) are not being caught be fastify. Cryptic `500` errors are being returned from the API 

`server.ts`
```ts
import Fastify from 'fastify'
import openapiGlue from 'fastify-openapi-glue'
import RouteHandler from './RouteHandler'

const glueOptions = {
  specification: `${__dirname}/schema.yaml`,
  service: new RouteHandler()
}

const fastify = Fastify({ logger: true })

fastify.register(openapiGlue, glueOptions)

const PORT = process.env.PORT || 4000

fastify.listen(PORT, (err, address) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  console.log(`Server listening at ${address}`)
})

```

`RouteHandler.ts`
```ts
import { FastifyReply, FastifyRequest } from 'fastify'
import context from './context'
import { castGetBooksParams, filterObj } from './utils'
import requireApiKey from './validations/requireApiKey'

const { booksService } = context.services

class RouteHandler {
  constructor() {}

  healthcheck = (_req: FastifyRequest, res: FastifyReply) => {
    return res.send({ message: 'ok' })
  }

  getBooks = async (req: FastifyRequest, res: FastifyReply) => {
    const params = castGetBooksParams(req.query as GetBooksParamsRaw)
    const books = await booksService.getBooks(params)
    return res.send(books)
  }

  createBook = async (req: FastifyRequest, res: FastifyReply) => {
    requireApiKey(req)

    const newBook = await booksService.createBook(req.body as CreateBookInput)
    return res.status(201).send(newBook)
  }

  getBook = async (req: FastifyRequest, res: FastifyReply) => {
    const book = await booksService.getBook(req.params as IdParams)
    return res.send(book)
  }

  updateBook = async (req: FastifyRequest, res: FastifyReply) => {
    requireApiKey(req)
    const params = req.params as IdParams
    const input = req.body as UpdateBookInput
    const book = await booksService.updateBook(params, input)
    return res.send(book)
  }

  deleteBook = async (req: FastifyRequest, res: FastifyReply) => {
    requireApiKey(req)
    const params = req.params as IdParams
    await booksService.deleteBook(params)
    return res.code(204).send()
  }
}

export default RouteHandler

```

example part of `schema.yaml` for `POST /books`

```yaml
/books:
  post:
      summary: 'Add a book'
      operationId: createBook
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookInput'
      responses:
        '201':
          description: 'Book created successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Unexpected error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

....

components:
  schemas:
    CreateBookInput:
      type: object
      required:
        - title
        - author
        - genre
        - yearPublished
      properties:
        title:
          type: string
          minLength: 1
        author:
          type: string
          minLength: 1
        genre:
          type: string
          minLength: 1
        yearPublished:
          type: integer
    
```

Trying to send a POST request to /books with a missing parameter returns a 500 error (expect 400 error with "missing" property type)

response from Fastify API
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "\"status\" is required!"
}
```

**Comment by seriousme** [comment]
Hi,

thanks for asking. 

To be honest I don't know why Fastify gives you the 500 instead of the 400.  The 500 should only be returned when an error is thrown,so something seems to be crashing.

As fastify-openapi-glue only passes config to fastify (it is not in the actual processing of the request) it must be something in fastify itself or in routeHandler.ts

Looking at your schema `/books` should be handled by `createBook`.
My guess would be that either `requireAPIkey` or `booksService.createBook` crashes.
Neither of them are present in https://github.com/Postman-Student-Program/restaurant-api-example/tree/chapter-3-persisting-data so I can't judge.

What you could try is to log the request passed to `createBook` and then create a test that sends this request to `requireAPIkey` and `booksService.createBook`. This way you avoid the error masking by Fastify.

Alternatively you could increase the loglevel of fastify to `debug` and see if that gives you more relevant info.

Hope this helps !
Hans

**Comment by clairefro** [comment]
Thanks so much for the reply. I tried commenting out the security elements of the schema to see if that was tripping it up, but no it's the same problem. 

I can see that the 400 error is recognized internally by fastify at one point, but somewhere along the way the statusCode becomes obscured. Still investigating. It may be a fastify bug and not fastify-openapi-glue

```
{"level":30,"time":1647287106440,"pid":26600,"hostname":"Claires-MBP","reqId":"req-1","res":{"statusCode":400},"err":{"type":"Error","message":"body must have required property 'title'","stack":"Error: body must have required property 'title'\n    at Object.<anonymous> (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify-openapi-glue/index.js:62:26)\n    at wrapValidationError (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/validation.js:105:17)\n    at validate (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/validation.js:86:12)\n    at preValidationCallback (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/handleRequest.js:90:18)\n    at handler (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/handleRequest.js:73:7)\n    at /Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/contentTypeParser.js:174:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)\n    at done (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/contentTypeParser.js:169:14)\n    at Parser.defaultJsonParser [as fn] (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/contentTypeParser.js:269:5)\n    at IncomingMessage.onEnd (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/contentTypeParser.js:248:27)","validation":[{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"title"},"message":"must have required property 'title'"}],"validationContext":"body"},"msg":"body must have required property 'title'"}
{"level":50,"time":1647287106444,"pid":26600,"hostname":"Claires-MBP","reqId":"req-1","err":{"type":"Error","message":"\"status\" is required!","stack":"Error: \"status\" is required!\n    at $main (eval at build (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fast-json-stringify/index.js:155:20), <anonymous>:182:15)\n    at handleError (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:587:9)\n    at onErrorHook (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:535:5)\n    at _Reply.Reply.send (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:129:5)\n    at defaultErrorHandler (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/fastify.js:91:9)\n    at handleError (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:566:20)\n    at onErrorHook (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:535:5)\n    at _Reply.Reply.send (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/reply.js:129:5)\n    at preValidationCallback (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/handleRequest.js:93:23)\n    at handler (/Users/claire.froelich@postman.com/code/postman/library-api-v2/node_modules/fastify/lib/handleRequest.js:73:7)"},"statusCode":400,"msg":"The serializer for the given status code failed"}
```

**Comment by clairefro** [comment]
Found out the problem was my schema was defining an `Error` as an object with a required property `status`, which is not natively added by fastify. 

BEFORE
```yaml
      Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum: [error]
        message:
          type: string
        errors:
          type: array
          items: {} # any type. This property supplied in case of request validation errors


```

AFTER
```yaml
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        errors:
          type: array
          items: {} # any type. This property supplied in case of request validation errors

```

**Comment by seriousme** [comment]
You might want to try bypassing `requireApiKey` as well to see if that solves your problem.
Fastify will validate the input against the schema and then call `createBook`

if createBook is not being called then it must be something in fastify or in the schema.

Hope this helps!
Hans

**Comment by seriousme** [comment]
Great to see you found the problem!

Good luck with your project!
Hans

**Comment by seriousme** [comment]
This default behaviour of AJV. Fastify uses AJV to validate the request against your schema.
You could try passing allErrors;true as AJV option.

See https://stackoverflow.com/questions/56364900/ajv-return-only-one-error-although-there-is-multiple

Kind regards,
Hans

**Comment by clairefro** [comment]
@seriousme THANK YOU. this worked: 
```ts
const glueOptions = {
  specification: `${__dirname}/schema.yaml`,
  service: new RouteHandler(),
  ajvOptions: {
    allErrors: true
  }
}
```

**Comment by seriousme** [comment]
Good to see it worked :-)
Keep in mind though that returning all errors will take more resources from your server and therefore potentially could make you a little more vulnerable to a denial of service or denial of wallet attack.

Kind regards,
Hans
